# Generated by Django 3.0.8 on 2020-12-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201217_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_desc',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_tags',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
