# Generated by Django 3.0.8 on 2020-12-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_faq_timing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timing',
        ),
    ]
