# Generated by Django 3.0.8 on 2020-12-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_delete_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_duration', models.DurationField()),
                ('time_duration1', models.TimeField()),
                ('time_duration2', models.TimeField()),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_posts', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, choices=[('True', 'True'), ('False', 'False')], null=True, upload_to='media/certificate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_posts', to='posts.Post')),
            ],
        ),
    ]
