# Generated by Django 3.0.8 on 2020-12-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_certificate_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/certificate'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='day_duration',
            field=models.CharField(max_length=100),
        ),
    ]
