# Generated by Django 3.0.8 on 2020-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201218_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='certificate',
            field=models.BooleanField(default=False),
        ),
    ]
