# Generated by Django 3.0.8 on 2020-12-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('EMI', 'EMI'), ('ONLINE', 'Online')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=150),
        ),
    ]
