# Generated by Django 3.0.8 on 2020-12-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_order_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='certificate',
        ),
    ]
