# Generated by Django 3.0.8 on 2020-12-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20201219_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderitems',
        ),
        migrations.AddField(
            model_name='order',
            name='orderitems',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Cart'),
        ),
    ]
