# Generated by Django 3.1.4 on 2021-01-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='day_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='time_duration1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='time_duration2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
