# Generated by Django 3.1.4 on 2021-01-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_post_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcat',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='posts.category'),
        ),
    ]
