# Generated by Django 3.1.4 on 2021-01-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20210104_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='more',
            field=models.BooleanField(default=False),
        ),
    ]
