# Generated by Django 3.1.4 on 2021-01-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20210105_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/catlogo'),
        ),
    ]
