# Generated by Django 3.1.4 on 2021-01-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='media/catlogo'),
        ),
    ]
