# Generated by Django 3.1.4 on 2021-01-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20210105_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slider_post',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subcategory',
        ),
    ]
