# Generated by Django 3.1.4 on 2021-01-06 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20210106_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculam',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acc_blog', to='posts.blog'),
        ),
        migrations.AddField(
            model_name='faq',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_blog', to='posts.blog'),
        ),
    ]
