# Generated by Django 3.1.4 on 2021-01-06 08:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_auto_20210106_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculam',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='blog',
        ),
        migrations.CreateModel(
            name='tcforblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tc_blog', to='posts.blog')),
            ],
        ),
    ]
