# Generated by Django 3.1.4 on 2021-01-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_auto_20210106_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blank_page',
            new_name='blankpage',
        ),
    ]
