# Generated by Django 3.1.4 on 2021-01-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='discount',
        ),
        migrations.AddField(
            model_name='promocode',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
