# Generated by Django 3.1.4 on 2021-01-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_auto_20210108_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='disc',
            field=models.BooleanField(default=False, verbose_name='Add In Disclaimer'),
        ),
    ]
