# Generated by Django 3.1.4 on 2021-01-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_auto_20210112_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
