# Generated by Django 3.1.4 on 2021-01-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0049_category_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='disc',
            field=models.BooleanField(default=False, verbose_name='Add In Disclaimer'),
        ),
    ]
