# Generated by Django 3.1.4 on 2021-01-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_auto_20210113_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankpage',
            name='disc',
            field=models.BooleanField(default=False, verbose_name='Add In Disclaimer'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='disc',
            field=models.BooleanField(default=False, verbose_name='Add In Disclaimer'),
        ),
        migrations.AlterField(
            model_name='maincourse',
            name='disc',
            field=models.BooleanField(default=False, verbose_name='Add In Disclaimer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='disc',
            field=models.BooleanField(default=False, verbose_name='Add In Disclaimer'),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='disc',
            field=models.BooleanField(default=False, verbose_name='Add In Disclaimer'),
        ),
    ]
