# Generated by Django 3.1.4 on 2021-01-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_auto_20210113_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo1',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='media/catlogo'),
        ),
        migrations.AddField(
            model_name='category',
            name='logo2',
            field=models.ImageField(blank=True, help_text='Optional', null=True, upload_to='media/catlogo'),
        ),
    ]
