# Generated by Django 3.1.4 on 2021-01-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_auto_20210122_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billingAddress1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billingCity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billingCountry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billingName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billingPostcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingAddress1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingCity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingCountry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingPostcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='token',
        ),
    ]
