# Generated by Django 3.1.4 on 2021-02-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0055_auto_20210122_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(blank=True)),
                ('content', models.CharField(max_length=500)),
                ('wp', models.BooleanField(default=False, verbose_name='Send Whatsapp Message')),
            ],
        ),
    ]
