# Generated by Django 3.1.4 on 2021-02-10 05:11

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0056_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='wp',
            field=models.BooleanField(default=True, verbose_name='Send Whatsapp Message'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=500, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
