# Generated by Django 3.1.4 on 2021-02-16 11:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0057_auto_20210210_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off', models.CharField(max_length=100, verbose_name='Total Off')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Sub Title')),
                ('price', models.CharField(max_length=100, verbose_name='Price')),
                ('desc', models.CharField(max_length=100, verbose_name='Description')),
                ('button_text', models.CharField(max_length=100, verbose_name='Button Text')),
                ('small_desc', models.CharField(max_length=100, verbose_name='Small Description')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=500, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
