# Generated by Django 3.1.4 on 2021-02-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0058_auto_20210216_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
