# Generated by Django 3.1.4 on 2021-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0059_offers_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='button_url',
            field=models.URLField(default='', max_length=500, verbose_name='Button Link'),
        ),
    ]
