# Generated by Django 3.0.8 on 2020-12-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top_three_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='button_text',
            field=models.CharField(default='Apply Now', max_length=20),
        ),
    ]
