# Generated by Django 3.0.8 on 2020-12-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_maincourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincourse',
            name='post',
        ),
        migrations.AddField(
            model_name='maincourse',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Post'),
        ),
    ]
