# Generated by Django 3.0.8 on 2020-12-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201214_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincourse',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='courseposts', to='posts.Post'),
        ),
    ]
