# Generated by Django 3.0.8 on 2020-12-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201214_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincourse',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='maincourse',
            field=models.ManyToManyField(blank=True, null=True, to='posts.MainCourse'),
        ),
    ]
