# Generated by Django 3.0.8 on 2020-12-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201214_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='maincourse',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.MainCourse'),
        ),
    ]
