# Generated by Django 3.0.8 on 2020-12-15 10:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201215_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_course',
        ),
        migrations.AddField(
            model_name='post',
            name='badge',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='emi_start_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='youtube',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Upcoming_batches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
