# Generated by Django 3.0.8 on 2020-12-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201215_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upcoming_batches',
            new_name='Accordion',
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube',
            field=models.URLField(default='', max_length=500),
        ),
    ]
