# Generated by Django 3.0.8 on 2020-12-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201215_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='why1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='why2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='why3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='why_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
