# Generated by Django 3.0.8 on 2020-12-15 10:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20201215_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='why1',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='why2',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='why3',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
