# Generated by Django 3.0.8 on 2020-12-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201215_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='old_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
