# Generated by Django 3.0.8 on 2020-12-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20201215_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxes_three',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
