# Generated by Django 3.0.8 on 2020-12-16 04:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20201215_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='why1',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='why2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='why3',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
