# Generated by Django 3.0.8 on 2020-12-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20201216_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Zip_Code',
            field=models.IntegerField(blank=True),
        ),
    ]
