# Generated by Django 3.0.8 on 2020-12-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20201216_1355'),
        ('posts', '0023_auto_20201216_1355'),
    ]

    operations = [
    ]
